[window]

startup_mode = "Maximized"

[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular"}
bold = { family = "RobotoMono Nerd Font", style = "Bold"}
italic = { family = "RobotoMono Nerd Font", style = "Italic"}
bold_italic = { family = "RobotoMono Nerd Font", style = "Bold Italic"}

size = 12

[cursor]
style = { shape = "Block", blinking = "Off"}

[colors]
cursor = { cursor = "#FFFFFF", text = "#000000"}

[colors.primary]
#foreground = "#000000"
#background = "#FFFFFF"

#background = "#0d1117"
background = "#03241A"
foreground = "#c8d3f5"

[keyboard]

bindings = [
            { key = "T", mods = "Control|Shift", action = "CreateNewWindow" },
#           { key = "W", mods = "Control|Shift", action = "Quit" },
            { key = "P", mods = "Alt|Shift", action = "Paste" },
            { key = "Y", mods = "Alt|Shift", action = "Copy" },
            { key = "M", mods = "Alt|Shift", action = "ToggleViMode"},

            { key = "Y", mods = "Alt|Shift", action = "ScrollLineUp" },
            { key = "E", mods = "Alt|Shift", action = "ScrollLineDown" },
]
